#服务端口与超时
server:
  port: 8080
  session-timeout: 1200
  undertow:
    accesslog:
      # 打开Undertow访问日志
      enabled: true
      # 访问日志所在目录
      dir: logs
    # 创建工作线程的I/O线程，默认为2或者CPU个数（有点像nginx的I/O线程）
    #io-threads:
    # 工作线程个数，默认为I/O线程个数的8倍
    #worker-threads:
    # HTTP POST内容最大长度，默认不限制
    #max-http-post-size:

#logback日志
logging:
  config: classpath:logback.xml

#actuator端口
management:
  server:
    port: 9001
  security:
    enabled: false
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      base-path: /monitor
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点(yml中*是特殊字符，需要引号)
        include: "*"
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always


