#服务端口与超时
server:
  port: 8080
  session-timeout: 1200
  jetty:
    accesslog:
      # 打开Tomcat访问日志
      enabled: true
      # 访问日志所在目录
      dir: logs
    # acceptors线程个数，用来接受访问请求，相当于工作线程
    #acceptors:
    # selectors线程个数，和CPU个数相关，默认是(可用CPU+1)/2，用于分配请求给工作线程
    #selectors:

#logback日志
logging:
  config: classpath:logback.xml

#actuator端口
management:
  server:
    port: 9001
  security:
    enabled: false
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      base-path: /monitor
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点(yml中*是特殊字符，需要引号)
        include: "*"
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always


